# Generated by Django 4.2.23 on 2025-11-01 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.TextField(null=True)),
                ('op1', models.CharField(max_length=10000, null=True)),
                ('op2', models.CharField(max_length=10000, null=True)),
                ('op3', models.CharField(max_length=10000, null=True)),
                ('op4', models.CharField(max_length=10000, null=True)),
                ('options', models.TextField(null=True)),
                ('file', models.CharField(max_length=400, null=True)),
                ('file_url', models.CharField(max_length=400, null=True)),
                ('time', models.CharField(default='0', max_length=400)),
                ('time_limit', models.CharField(default='30', max_length=400)),
                ('k', models.CharField(default='1', max_length=400)),
                ('p', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.lesson')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
