# Generated by Django 4.2.23 on 2025-08-23 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zquestion',
            name='time',
            field=models.CharField(default='0', max_length=400),
        ),
    ]
