# Generated by Django 4.2.23 on 2025-08-23 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0002_zquestion_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='zquestion',
            name='duration',
            field=models.CharField(default='0', max_length=400),
        ),
    ]
