# Generated by Django 4.2.23 on 2025-08-23 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0003_zquestion_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zquestion',
            old_name='duration',
            new_name='time_limit',
        ),
    ]
