# Generated by Django 4.2.23 on 2025-08-23 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0004_rename_duration_zquestion_time_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zquestion',
            name='time_limit',
            field=models.CharField(default='30', max_length=400),
        ),
    ]
